// Import the OneSignal service worker script first.
importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');

// This file is required by next-pwa to be present in the public folder.
// It is automatically generated by the next-pwa plugin.
// We are using a custom service worker to integrate OneSignal.
// All other PWA logic is handled by next-pwa through its manifest injection.

// The following is needed for next-pwa to inject its precache manifest.
// DO NOT REMOVE THIS OR THE BUILD WILL FAIL.
// next-pwa will find this variable and replace it with the precache manifest.
self.__WB_MANIFEST;
